### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by NiK7160** [oleksandrblazhko/ai-216-semerenko#14]
Завдання 1
1) Потреба - Отримання даних
2) Отримання даних є доступним для користувача, оскільки існує багато шляхів для вирішення цього питання, наприклад електронна пошта, хмарні сховища тощо. Отримання даних є зрозумілим для користувача, оскільки йому не потрібно докладати багато зусиль для їх отримання, просто залишити запит на їх отримання, після чого через деякий час йому нададуть всю необхідну інформацію у зручному для нього вигляді. Отримання даних нічого не коштує для користувача, йому не потрібно платити для отримання даних. Проте протягом робочого дня користувач може не отримати всіх необхідних для роботи даних, тому актуальність визначена як «запізно».

Завдання 2
1) Мета: «дотримуватися актуальності у отриманні даних для зацікавленості музикою під час безпечної роботи при комфортній вологості навколишнього середовища»
2) Отримувати інформацію в зручному для користувача форматі дозволяє йому краще та зручніше розвивати свою музикальну зацікавленість, а також зробити процес написання музики та слів максимально ефективним. Вільний доступ до різноманітних джерел пошуку інформації дозволяє співробітнику офісу швидше шукати необхідну інформацію у відповідь на запити користувачів, тим самим це дозволяє підвищити актуальність даних для користувачів, оскільки їх запити швидше обробляються. Регулювання рівня вологості в застосунку дозволяє технічному персоналу офісу швидше, зручніше та більш детально налаштовувати вологість навколишнього середовища, завдяки чому підвищується рівень комфорту для роботи користувача.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 4 бали
